name: Deploy to S3

on:
  push:
    branches:
      - dev

  workflow_dispatch:
    branches:
      - main

jobs:
  build-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      # - name: Cache node-modules
      #   uses: actions/cache@v3
      #   with:
      #     path:
      #     key:
      #     restore-keys:

      - name: Install Dependencies
        run: npm ci

      - name: Build the Application
        run: npm run build

      - name: Upload Build Directory
        uses: actions/upload-artifact@v3
        with:
          name: build-dir
          path: dist/

  push-to-s3:
    needs: build-application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download Build Directory
        uses: actions/download-artifact@v3
        with:
          name: build-dir
          path: dist/

      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Push to S3 Bucket
        run: aws s3 sync dist/ s3://www.commite.dev
